api = "0.4"

[buildpack]
id = "jimcru21/custombinaries"
version = "1.0.1"
name = "Custom Binary Buildpack"
homepage = "https://github.com/jimcru21/heroku-buildpack-custom-binaries"
description = "Installs custome binaries for further builds and runtime"
keywords = ["custom binaries", "packages", "ubuntu"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
