api = "0.4"

[buildpack]
version = "0.1.0"
name = "apt Packages Buildpack"
homepage = "https://github.com/jimcru21/heroku-buildpack-custom-binaries"
description = "Installs custom binaries"

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
